import { createPartyOperationsSocketMessageHandler } from "../core/socket-message-handler.js";

export function buildLegacyPartyOperationsSocketRouteDeps({
  settings,
  refreshScopeKeys,
  normalizeRefreshScopeList,
  setLootClaimActorSelection,
  normalizeLootClaimActorId,
  setLootClaimRunSelection,
  normalizeLootClaimRunId,
  waitForLootClaimsPublished,
  buildLootClaimsContext,
  logUiDebug,
  promptLootClaimsDialogForPlayer,
  openOperationsLootClaimsTabForPlayer,
  openRestWatchUiForCurrentUser,
  refreshOpenApps,
  schedulePendingSopNoteSync,
  syncMerchantBarterStatusForOpenDialogs,
  getSocketRequester,
  sanitizeSocketIdentifier,
  normalizeSocketActivityType,
  getRestActivities,
  setModuleSettingWithLocalRefreshSuppressed,
  emitSocketRefresh,
  normalizeSocketRestRequest,
  restOps,
  clampSocketText,
  socketNoteMaxLength,
  normalizeRestNoteSaveSource,
  applyRestRequest,
  getRestWatchState,
  game,
  resolveRequester,
  canUserControlActor,
  stampUpdate,
  scheduleIntegrationSync,
  applyPlayerActivityUpdateRequestFeature,
  normalizeSocketMarchRequest,
  marchOps,
  marchRanks,
  applyMarchRequest,
  getMarchingOrderState,
  isMarchingOrderPlayerLocked,
  applyPlayerSettingWriteRequestFeature,
  canAccessAllPlayerOps,
  isWritableModuleSettingKey,
  foundry,
  moduleId,
  suppressNextSettingRefresh,
  getRefreshScopesForSettingKey,
  logUiFailure,
  applyPlayerFolderOwnershipWriteRequestFeature,
  constDocOwnershipLevels,
  ui,
  applyPlayerSopNoteRequestFeature,
  sopKeys,
  updateOperationsLedger,
  setSharedSopNoteText,
  applyPlayerOperationsLedgerWriteRequestFeature,
  buildDefaultOperationsLedger,
  applyPlayerDowntimeSubmitRequestFeature,
  getOperationsLedger,
  ensureDowntimeState,
  normalizeDowntimeSubmission,
  applyDowntimeSubmissionForUser,
  applyPlayerDowntimeClearRequestFeature,
  canUserManageDowntimeActor,
  applyPlayerDowntimeCollectRequestFeature,
  applyDowntimeCollectionForUser,
  getDowntimeCollectionSummary,
  applyPlayerMerchantBarterRequest,
  applyPlayerMerchantTradeRequest,
  applyPlayerLootClaimRequest,
  applyPlayerLootCurrencyClaimRequest,
  applyPlayerLootVouchRequest
} = {}) {
  return {
    settings,
    refreshScopeKeys,
    normalizeRefreshScopeList,
    setLootClaimActorSelection,
    normalizeLootClaimActorId,
    setLootClaimRunSelection,
    normalizeLootClaimRunId,
    waitForLootClaimsPublished,
    buildLootClaimsContext,
    logUiDebug,
    promptLootClaimsDialogForPlayer,
    openOperationsLootClaimsTabForPlayer,
    openRestWatchUiForCurrentUser,
    refreshOpenApps,
    schedulePendingSopNoteSync,
    syncMerchantBarterStatusForOpenDialogs,
    getSocketRequester,
    sanitizeSocketIdentifier,
    normalizeSocketActivityType,
    getRestActivities,
    setModuleSettingWithLocalRefreshSuppressed,
    emitSocketRefresh,
    normalizeSocketRestRequest: (request) => normalizeSocketRestRequest(request, {
      restOps,
      sanitizeSocketIdentifier,
      clampSocketText,
      noteMaxLength: socketNoteMaxLength,
      normalizeRestNoteSaveSource
    }),
    applyRestRequest: (request, requesterRef) => applyRestRequest(request, requesterRef, {
      getRestWatchState,
      game,
      resolveRequester,
      canUserControlActor,
      stampUpdate,
      setModuleSettingWithLocalRefreshSuppressed,
      settings,
      scheduleIntegrationSync,
      refreshOpenApps,
      refreshScopeKeys,
      emitSocketRefresh,
      logUiDebug
    }),
    applyPlayerActivityUpdateRequest: (message) => applyPlayerActivityUpdateRequestFeature(message, null, {
      getSocketRequester,
      sanitizeSocketIdentifier,
      normalizeSocketActivityType,
      getRestActivities,
      setModuleSettingWithLocalRefreshSuppressed,
      settings,
      refreshOpenApps,
      refreshScopeKeys,
      emitSocketRefresh
    }),
    normalizeSocketMarchRequest: (request) => normalizeSocketMarchRequest(request, {
      marchOps,
      marchRanks,
      sanitizeSocketIdentifier,
      clampSocketText,
      noteMaxLength: socketNoteMaxLength
    }),
    applyMarchRequest: (request, requesterRef) => applyMarchRequest(request, requesterRef, {
      getMarchingOrderState,
      game,
      resolveRequester,
      canUserControlActor,
      isMarchingOrderPlayerLocked,
      stampUpdate,
      setModuleSettingWithLocalRefreshSuppressed,
      settings,
      scheduleIntegrationSync,
      refreshOpenApps,
      refreshScopeKeys,
      emitSocketRefresh,
      logUiDebug
    }),
    applyPlayerSettingWriteRequest: (message, requesterRef) => applyPlayerSettingWriteRequestFeature(message, requesterRef, {
      resolveRequester,
      canAccessAllPlayerOps,
      isWritableModuleSettingKey,
      game,
      foundry,
      moduleId,
      suppressNextSettingRefresh,
      refreshOpenApps,
      getRefreshScopesForSettingKey,
      emitSocketRefresh,
      logUiFailure
    }),
    applyPlayerFolderOwnershipWriteRequest: (message, requesterRef) => applyPlayerFolderOwnershipWriteRequestFeature(message, requesterRef, {
      resolveRequester,
      canAccessAllPlayerOps,
      sanitizeSocketIdentifier,
      constDocOwnershipLevels,
      game,
      foundry,
      ui,
      refreshOpenApps,
      refreshScopeKeys,
      emitSocketRefresh,
      moduleId
    }),
    applyPlayerSopNoteRequest: (message, requesterRef) => applyPlayerSopNoteRequestFeature(message, requesterRef, {
      resolveRequester,
      sopKeys,
      clampSocketText,
      noteMaxLength: socketNoteMaxLength,
      updateOperationsLedger,
      setSharedSopNoteText
    }),
    applyPlayerOperationsLedgerWriteRequest: (message, requesterRef) => applyPlayerOperationsLedgerWriteRequestFeature(message, requesterRef, {
      resolveRequester,
      buildDefaultOperationsLedger,
      foundry,
      setModuleSettingWithLocalRefreshSuppressed,
      settings,
      scheduleIntegrationSync,
      refreshOpenApps,
      refreshScopeKeys,
      emitSocketRefresh
    }),
    applyPlayerDowntimeSubmitRequest: (message, requesterRef) => applyPlayerDowntimeSubmitRequestFeature(message, requesterRef, {
      resolveRequester,
      getOperationsLedger,
      ensureDowntimeState,
      normalizeDowntimeSubmission,
      sanitizeSocketIdentifier,
      applyDowntimeSubmissionForUser
    }),
    applyPlayerDowntimeClearRequest: (message, requesterRef) => applyPlayerDowntimeClearRequestFeature(message, requesterRef, {
      resolveRequester,
      sanitizeSocketIdentifier,
      game,
      canUserManageDowntimeActor,
      updateOperationsLedger,
      ensureDowntimeState
    }),
    applyPlayerDowntimeCollectRequest: (message, requesterRef) => applyPlayerDowntimeCollectRequestFeature(message, requesterRef, {
      resolveRequester,
      sanitizeSocketIdentifier,
      applyDowntimeCollectionForUser,
      ui,
      getDowntimeCollectionSummary
    }),
    applyPlayerMerchantBarterRequest,
    applyPlayerMerchantTradeRequest,
    applyPlayerLootClaimRequest,
    applyPlayerLootCurrencyClaimRequest,
    applyPlayerLootVouchRequest
  };
}

export function createLegacyPartyOperationsSocketMessageHandler({
  createSocketMessageHandler = createPartyOperationsSocketMessageHandler,
  game = globalThis.game,
  applyPlayerGatherRequest,
  promptLocalGatherCheckRoll,
  promptLocalGatherYieldRoll,
  resolvePendingGatherCheckRequest,
  resolvePendingGatherYieldRequest,
  ...routeDeps
} = {}) {
  return createSocketMessageHandler({
    game,
    applyPlayerGatherRequest,
    promptLocalGatherCheckRoll,
    promptLocalGatherYieldRoll,
    resolvePendingGatherCheckRequest,
    resolvePendingGatherYieldRequest,
    routeSocketDeps: buildLegacyPartyOperationsSocketRouteDeps({
      game,
      ...routeDeps
    })
  });
}
